name: Twin Moon Tattoos
favicon: null
layout_spectrum: 0.3918709824793041
typography_spectrum: 0.5630932280328125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2670665914192796
  lightness: 0.13207610114477575
  saturation: 0.29491942399181426
  rhythmicContrast: 0.8654192122630775
purpose: []
