name: Twin Moon Tattoos
favicon: null
layout_spectrum: 0.25038
typography_spectrum: 0.5630932280328125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5c5c5c'
    - '#441e1d'
    - '#95937a'
  brandStrength: 0.25
  lightness: 0.13207610114477575
  saturation: 0.29491942399181426
  rhythmicContrast: 0.8654192122630775
purpose: []
